CREATE TABLE  `twitter`.`tweets` (
`id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`username` VARCHAR(255) NOT NULL ,
`content` VARCHAR(255) NOT NULL ,
`created` DATETIME NULL DEFAULT NULL
) ENGINE = INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE `twitter`.`follows` (
`id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`followed_name` VARCHAR(255) NOT NULL ,
`follower_name` VARCHAR(255) NOT NULL ,
`created` DATETIME NULL DEFAULT NULL
) ENGINE = INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE `twitter`.`users` (
`id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`username` VARCHAR(255) NOT NULL ,
`password` VARCHAR(255) NOT NULL ,
`created` DATETIME NULL DEFAULT NULL
) ENGINE = INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;
